# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi-machine sample setup
Vagrant.configure("2") do |config|
  config.vm.define :kali do |kali|
    kali.vm.box = "kalilinux/rolling"
    kali.vm.box_check_update = false
    kali.vm.network :private_network, ip: "10.0.0.12"
    kali.vm.hostname = "p2-kali"
    kali.vm.provider "virtualbox" do |vb|
      vb.name = "Project 2 Kali 2024 Rolling"
      vb.gui = true
      vb.memory = 4096
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--vram", 128]
    end
    kali.vm.provider "vmware_workstation" do |vmw|
      vmw.gui = true
      vmw.memory = 4096
      vmw.cpus = 2
    end
    kali.vm.provision "shell", path: "../shell-scripts/kali.sh"
  end

  config.vm.define :metasploitable3 do |metasploitable3|
    metasploitable3.vm.box = "rapid7/metasploitable3-ub1404"
    metasploitable3.vm.box_version = "0.1.12-weekly"
    metasploitable3.ssh.username = "vagrant"
    metasploitable3.ssh.password = "vagrant"
    metasploitable3.vm.box_check_update = false
    metasploitable3.vm.network :private_network, ip: "10.0.0.13"
    metasploitable3.vm.synced_folder ".", "/vagrant", disabled: true
    metasploitable3.vm.hostname = "p2-metasploitable3"
    metasploitable3.vm.provider "virtualbox" do |vb|
      vb.name = "Project 2 Metasploitable 3 Ubuntu 14.04"
      vb.gui = false
      vb.memory = 1024
      vb.cpus = 1
    end
    metasploitable3.vm.provider "vmware_workstation" do |vmw|
      vmw.gui = false
      vmw.memory = 1024
      vmw.cpus = 1
    end
  end
end