# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "kalilinux/rolling"
  config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Kali 2024 Rolling"
    vb.gui = true
    vb.memory = 4096
    vb.cpus = 2
  end
  config.vm.provider "vmware_workstation" do |vmw|
    vmw.gui = true
    vmw.memory = 4096
    vmw.cpus = 2
  end
  config.vm.provision "shell", path: "../shell-scripts/kali.sh"
end