# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "rapid7/metasploitable3-ub1404"
  config.vm.box_version = "0.1.12-weekly"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  # config.vm.box_check_update = false
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network"
  # config.vm.synced_folder "../data", "/vagrant_data"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |vb|
    vb.name = "Metasploitable3 Ubuntu 14.04"
    vb.gui = true
    vb.memory = 512
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--vram", 16]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end
  config.vm.provider "vmware_workstation" do |vmw|
    vmw.gui = true
    vmw.memory = 512
    vmw.cpus = 1
  end
end